# home assistant automation

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:${HOMEASSISTANT_VERSION}
    container_name: ${HOMEASSISTANT_NAME}
    env_file:
      - home_assistant/.env
      - home_assistant/.env.manager
    volumes:
      - ${HOMEASSISTANT_FOLDER}:/config
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - "${HOMEASSISTANT_PORT}"    # here for docs clarity. "ports:" does not do anything with "network_mode: host"
    environment:
      - TZ=America/Los_Angeles
    restart: unless-stopped
    network_mode: host
