# home assistant automation

services:
  homeassistant:
    image: 
    container_name: homeassistant
    env_file: .env
    volumes:
      - home_assistant_folder_path
    # ports:
    #   - "port_nbr"                # "ports:" does not do anything with "network_mode: host"
    environment:
      - TZ=timezone_for_dt
    restart: 
    network_mode: host              # assigned to a default port. allows container to share the same network stack as the host (local)

